# -*- coding: utf-8 -*-
"""PRODUCT VIEW ANALYSER.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y12HScvJX0YzUVvUV7KKMMylRk6uglO5
"""

!pip install transformers
from transformers import pipeline
import pandas as pd

s=pipeline("sentiment-analysis")
reviews="""The laptop starts quickly and works smoothly for daily tasks.
The screen quality is clear and good for watching videos.
Battery backup is average and needs charging often.
The fan makes noise when many apps are running.
Overall, it is a good laptop for students but not for gaming.
"""

sen=reviews.split(".")
pros=[]
cons=[]
for t in sen:
  t=t.strip()
  if t=="":
    continue
  res=s(t)[0]
  if res["label"]=="POSITIVE":
    pros.append(t)
  elif res["label"]=="NEGATIVE":
    cons.append(t)

pros=pros[:2]
cons=cons[:2]
df=pd.DataFrame({"Pros":pros,"Cons":cons})
df