# -*- coding: utf-8 -*-
"""SENTENCE SIMILARITY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yIKZ2UbEX_P8WetUBlWFVgn9xzGytXPu
"""

!pip install sentence_transformers

from sentence_transformers import SentenceTransformer, util
model=SentenceTransformer('all-MiniLM-L6-v2')
t1=input("Enter text 1: ")
t2=input("enter text 2: ")
em1=model.encode(t1)
em2=model.encode(t2)
sim=util.cos_sim(em1,em2)
print("\nSimilarity Score:",round(float(sim),2))
if sim>0.75:
  print("Similarity level: High")
elif sim>0.4:
    print("Similarity level: Medium")
else:
    print("Similarity level: low")